### ISSUE TITLE
Is callling multiple samples or invariant sites possible?

### ISSUE THREAD

**Issue by ShannonBrandt** [hippo-yf/bsgenova#3]
Good day, 
Thank you for this really neat piece of software.
I have used Bsgenova to call SNPS in >200 individuals, I then merged them using BCFtools (As i did not see any option to call multiple files at once using Bsgenova) into a multi-sample VCF. This has led to a mutli-sample VCF with many (./.) positions, which are likely homozygous with the reference allele (thus should be 0/0). This can however not be assumed to be true of all the positions (especially as I am working with sequence capture data). I saw that there is no option (that I am aware of) for Bsgenova to call invariant sites when calling the initial single VCF per sample - which would then call 0/0. 

Is there a reason that there is no functionality to allow for calling multiple samples at once, or alternatively calling invariant sites? 

I am trying to understand if there is some biological or genetic reasoning behind this that I am missing, or else I will try to create a custom python script to retrieve the 'missing' from the ATCGmaps to fill the VCF for 0/0 sites and leave truly missing sites as ./. Or do you perhaps have a better solution to this? 

Thank you so much!

**Comment by hippo-yf** [comment]
1, I have recently fixed the bugs of vcf file format, hope you used the latest bsgenova. Also, GQ is modified and GQH is added
2, calling each sample instead of multiple samples is convenient in compter clutser; also, calling from multiple samples at once is intractable in programing, no existing software as I know did this job
3, you can simplely use `bcftools merge --missing-to-ref` to treat all missing sites (sites of low read depth) and insignificant sites as  the same with referecen 0/0
4, If you must distinguish missing sites and insignificant sites, set p-value threshold to 1, then all covered/non-missing sites will be outputed, then bcftools merge all vcf files, last, filter the sites with proper QUAL/GQ/GQH threshold; or you can write a script to query the read depth of sites in merged vcf file, to decide marker it 0/0 or ./.

**Comment by ShannonBrandt** [comment]
Thank you for the response to this. I did write a script to distinguish 0/0 from ./.. Thank you for the useful software.
